import java.util.ListResourceBundle;

public class Language_cat extends ListResourceBundle {
    @Override
    public Object[][] getContents ( ) {
        return contents;
    }

    private Object[][] contents = {
            {"add", "Afegir ruta"},
            {"sum_of_distance", "Suma de distàncies de ruta"},
            {"history", "Història"},
            {"info", "Informació"},
            {"execute_script", "Executar script"},
            {"clear", "Clear Col·lecció"},
            {"filter_less_than_distance", "Mostra rutes més curtes"},
            {"print_ascending", "Mostra la col·lecció en ordre ascendent"},
            {"remove_lower", "Eliminar rutes superiors a les especificades"},
            {"remove_greater", "Eliminar rutes inferiors a les especificades"},
            {"blup", "No dubteu davant l'estrès i l'estrès"},
            {"add1", "Afegir ruta"},
            {"sum_of_distance1", "Suma de distància de rutes"},
            {"history1", "History"},
            {"info1", "Informació"},
            {"execute_script1", "Executa l'script"},
            {"clear1", "Clear Col·lecció"},
            {"filter_less_than_distance1", "Mostra rutes amb distàncies més curtes"},
            {"print_ascending1", "Mostra la col·lecció en ordre ascendent"},
            {"remove_lower1", "Eliminar rutes superiors a les especificades"},
            {"remove_greater1", "Eliminar rutes inferiors a les especificades"},
            {"blup1", "Podeu disparar i alleujar l'estrès"},
            {"user", "Usuari:"},
            {"user1", "Usuari:"},
            {"language", "Seleccioneu un idioma"},
            {"language1", "Choose language"},
            {"graphics", "Graphics"},
            {"collection", "Collection"},
            {"owner", "Owner"},
            {"name", "Name Route"},
            {"id", "id"},
            {"coordinateX", "X actual"},
            {"coordinateY", "Y actual"},
            {"creationDate", "Data de creació"},
            {"fromName", "Nom de l'enviament"},
            {"fromX", "Sortida X"},
            {"fromY", "Depart Y"},
            {"toName", "Nom de l'arribada"},
            {"toX", "Arribada X"},
            {"toY", "Arrival Y"},
            {"distance", "Distance"},
            {"connect", "Establir una connexió..."},
            {"enterAddress", "Introduïu l’adreça"},
            {"enterPort", "Entra al port"},
            {"Ууууу, в адресе не должно быть пробелов", "Uuuuu, no hi ha d'haver espais a l'adreça"},
            {"Порт с пробелами, серьезно? Зачем?", "Port amb espais, seriosament? Per què?"},
            {"Такого адреса, к сожалению, не существует", "Malauradament, aquesta adreça no existeix"},
            {"Порт должен быть циферкой", "Port ha de ser un número"},
            {"Соединение установлено", "Connexió establerta"},
            {"buttonConnect", "Сonnectar"},
            {"inLK", "Accés al compte"},
            {"user", "Login"},
            {"pass", "Contrasenya"},
            {"signUp", "Registre"},
            {"signIn", "Login"},
            {"Пользователь с таким логином уже зарегистрирован. Может, вам стоит авторизоваться?", "Ja s’ha registrat un usuari amb un inici de sessió. Potser haureu d’iniciar sessió?"},
            {"Вы успешно зарегистрировались", "Вы успешно зарегистрировались", "Us heu registrat correctament"},
            {"Пользователь с таким логином не зарегистрирован", "Un usuari amb un inici de sessió no està registrat"},
            {"Вы успешно авторизовались", "Heu entrat correctament"},
            {"Вы ввели неправильный пароль", "Heu introduït la contrasenya equivocada"},
            {"Вам следует использовать только латиницу( Вините helios, не меня", "Només heu d’utilitzar l’alfabet llatí (Blame helios, no jo)"}
    };

}
